import Head from "next/head";
import Navigation from './Navigation'

export default function AppLayout({ children }) {
  return (
    <>
      <Head>
        <title>Onboarding Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className="container">{children}</main>
    </>
  );
}
